Bugfix: Match Multiple paths.
coala/git-url-parse pull request #37
Opened 2019-06-10 02:45 UTC by HaloGithub

Since GitLab has `Group` and `SubGroup` concept, and repo can be under SubGroup, so the repo URL can be `https://gitlab.example.com/group/sub-group/example.git`.

2019-07-08 12:00 UTC, jayvdb commented on test/conftest.py
> +        'https://github.com/Group/Owner/Stouts.openvpn.git': {
test case shouldnt be github ; it should be gitlab

2019-07-08 12:01 UTC, jayvdb requested changes
Also commit message would be better noting this is a new feature, as it isnt a bug in existing supported functionality.  GitLab has added features which havent yet been added here

2019-07-10 16:37 UTC, HaloGithub commented
Hi @jayvdb, thanks for your suggestion and I have create another one PR #40  of this instead.

2019-07-10 16:37 UTC, closed without merging

2023-05-08 11:14 UTC, TonisPiip commented
[jayvdb](https://github.com/jayvdb) Can we get some progress on this? Weird how this issue is just closed, but it's a pretty clear missed use-case for this software.